In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/StudentsPerformance.csv")

In [41]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'race/Ethnicity'],
      dtype='object')

In [47]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,race/Ethnicity,total score,average score
0,female,group B,bachelor's degree,standard,none,72,72,74,group b,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,group c,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,group b,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,group a,148,49.333333
4,male,group C,some college,standard,none,76,78,75,group c,229,76.333333

In [51]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
race/Ethnicity                 0
total score                    0
average score                  0
dtype: int64

In [52]:
df.duplicated().sum()

np.int64(0)

In [53]:

print("\nShape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

Shape:
(1000, 11)

Column Names:
Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'race/Ethnicity', 'total score', 'average score'],
      dtype='object')

Data Types:
gender                          object
race/ethnicity                  object
parental level of education     object
lunch                           object
test preparation course         object
math score                       int64
reading score                    int64
writing score                    int64
race/Ethnicity                  object
total score                      int64
average score                  float64
dtype: object

In [54]:
catagory_column = [
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
]

In [62]:
for col in catagory_column:
    df[col] = df[col].astype(str).str.strip().str.lower().str.title()

In [57]:
print(df[cat_cols].isnull().sum())

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
dtype: int64

In [58]:
score_columns = [
    "math score",
    "reading score",
    "writing score"
]

In [59]:
df["total score"] = (
    df["math score"]
    + df["reading score"]
    + df["writing score"]
)

In [44]:
df["average score"] = df["total score"] / 3

In [60]:
for col in score_columns:

    print("\nSubject:", col)

    print("Mean:", df[col].mean())

    print("Median:", df[col].median())

    print("Standard Deviation:", df[col].std())

    print("Q1:", df[col].quantile(0.25))

    print("Q2 (Median):", df[col].quantile(0.50))

    print("Q3:", df[col].quantile(0.75))

Subject: math score
Mean: 66.089
Median: 66.0
Standard Deviation: 15.163080096009468
Q1: 57.0
Q2 (Median): 66.0
Q3: 77.0

Subject: reading score
Mean: 69.169
Median: 70.0
Standard Deviation: 14.60019193725222
Q1: 59.0
Q2 (Median): 70.0
Q3: 79.0

Subject: writing score
Mean: 68.054
Median: 69.0
Standard Deviation: 15.195657010869642
Q1: 57.75
Q2 (Median): 69.0
Q3: 79.0